name: check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  shell:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Check scripts
        run: ./tests/check.sh
